/** Canonical system-design interview prompts. */
export const DESIGN_PROMPTS: { title: string; prompt: string }[] = [
  { title: "Design a URL Shortener", prompt: "Design a URL shortener like bit.ly. Focus on the short-code scheme, redirect path latency, analytics, and scaling reads." },
  { title: "Design Twitter / X feed", prompt: "Design the home timeline for Twitter. Focus on fan-out on write vs read, the celebrity problem, and feed ranking hooks." },
  { title: "Design WhatsApp", prompt: "Design a 1:1 and group chat system. Focus on message delivery/ordering, online presence, offline delivery, and end-to-end encryption implications." },
  { title: "Design a Rate Limiter", prompt: "Design a distributed rate limiter as a service. Focus on the algorithm, the shared counter store, and correctness at window boundaries." },
  { title: "Design a News Feed (Instagram-style)", prompt: "Design a photo-sharing news feed. Focus on the feed generation strategy, media storage/CDN, and pagination." },
  { title: "Design Uber (matching)", prompt: "Design the rider-driver matching system. Focus on geospatial indexing, real-time location updates, and dispatch." },
  { title: "Design a Notification System", prompt: "Design a system that sends push / email / SMS notifications at scale. Focus on fan-out, provider failover, dedupe, and user preferences." },
  { title: "Design Dropbox / file sync", prompt: "Design file storage and sync across devices. Focus on chunking, dedupe, conflict resolution, and metadata vs blob storage." },
  { title: "Design a Web Crawler", prompt: "Design a large-scale web crawler. Focus on the URL frontier, politeness, dedupe, and freshness." },
  { title: "Design Ticketmaster", prompt: "Design a system for selling event tickets. Focus on inventory reservation, preventing double-booking, and handling flash-sale spikes." },
  { title: "Design a Distributed Cache", prompt: "Design a Redis-like distributed cache. Focus on partitioning, replication, eviction, and consistency during resharding." },
  { title: "Design a Key-Value Store", prompt: "Design a distributed KV store. Focus on partitioning (consistent hashing), replication, the consistency model, and read/write quorums." },
  { title: "Design YouTube", prompt: "Design video upload, transcoding and streaming. Focus on the transcoding pipeline, adaptive bitrate, CDN, and metadata vs blob storage." },
  { title: "Design Google Docs", prompt: "Design real-time collaborative editing. Focus on OT vs CRDT, presence, offline edits, and document persistence." },
  { title: "Design a Payment System", prompt: "Design the core of a payments platform (charge, refund, payout). Focus on ledger design, idempotency, double-entry accounting, and reconciliation." },
  { title: "Design Slack", prompt: "Design team messaging with channels, threads and search. Focus on real-time delivery fan-out, unread counts, and message search." },
  { title: "Design an Ad Click Aggregator", prompt: "Design a system that counts ad impressions and clicks at scale with near-real-time and batch-accurate views. Focus on streaming aggregation, idempotency, and late data." },
  { title: "Design a Distributed Job Scheduler", prompt: "Design a cron-like scheduler that runs millions of jobs reliably. Focus on time-wheel vs DB polling, exactly-once triggering, and worker failure." },
  { title: "Design Search Autocomplete", prompt: "Design type-ahead search suggestions at scale. Focus on the trie / ngram index, ranking, freshness, and per-request latency." },
  { title: "Design an API Gateway", prompt: "Design an API gateway: auth, rate limiting, routing, retries and observability. Focus on where each concern lives and failure isolation." },
  { title: "Design a Metrics / Monitoring System", prompt: "Design a Prometheus-like metrics system. Focus on time-series storage, cardinality, downsampling, and the query path." },
  { title: "Design Airbnb Search + Booking", prompt: "Design listing search with availability and a booking flow. Focus on the search index, calendar/availability, and preventing double-booking." },
  { title: "Design a Live-Streaming Platform (Twitch)", prompt: "Design low-latency live video with chat. Focus on ingest, the transcoding ladder, edge distribution, and chat fan-out." },
  { title: "Design a Collaborative Whiteboard (Figma-lite)", prompt: "Design a multiplayer canvas. Focus on CRDT/state sync, cursor presence, large-document performance, and conflict handling." },
  { title: "Design a Distributed Lock / Coordination Service", prompt: "Design a service like ZooKeeper/etcd. Focus on consensus (Raft), leader election, watches, and session/lease expiry." },
];
